name: On PR merged

on:
  push:
    branches:
      - main

jobs:
  replace_artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Find the merged PR number
        uses: jwalton/gh-find-current-pr@v1
        id: findPR
        with:
          state: closed

      - name: Download artifact from PR
        uses: dawidd6/action-download-artifact@v2
        with:
          name: output-${{steps.findPR.outputs.number}}
          workflow: ci.yml
          pr: ${{steps.findPR.outputs.number}}

      - name: Upload file
        uses: actions/upload-artifact@v3
        with:
          name: main
          path: output.txt
